### ISSUE TITLE
Named entity labels do not follow IOB2

### ISSUE THREAD

**Issue by nljubesi** [clarinsi/classla-stanfordnlp#13]
There are very infrequent cases where there are I- tags in the NER output that do not have preceding B- tags of the same type.

There should be one process after the NER predictions are made to modify the first I-x that has no preceding B-x into B-x.

**Comment by TomazErjavec** [comment]
For the record, this bug just bit me, and it would indeed be good if the fix were implemented, as down-stream programs rely on valid B, I sequences. Debugging what went wrong can take a lot of time, not to mention that every user must then implement the fix themselves, rather than having it done only once in CLASSLA. 

In case it helps, using the latest release, the minimal pipeline that reproduces the bug was `classla.Pipeline('sl', processors='tokenize,ner')`  and offending sentence / output is:
```
# newpar id = 1
# sent_id = 1.1
# text = Ustanovil je dom za šolsko invalidno mladino v Kamniku (1947).
1       Ustanovil       _       _       _       _       _       _       _       NER=O
2       je      _       _       _       _       _       _       _       NER=O
3       dom     _       _       _       _       _       _       _       NER=I-ORG
4       za      _       _       _       _       _       _       _       NER=I-ORG
5       šolsko  _       _       _       _       _       _       _       NER=I-ORG
6       invalidno       _       _       _       _       _       _       _       NER=I-ORG
7       mladino _       _       _       _       _       _       _       NER=I-ORG
8       v       _       _       _       _       _       _       _       NER=I-ORG
9       Kamniku _       _       _       _       _       _       _       NER=I-ORG
10      (       _       _       _       _       _       _       _       NER=O|SpaceAfter=No
11      1947    _       _       _       _       _       _       _       NER=O|SpaceAfter=No
12      )       _       _       _       _       _       _       _       NER=O|SpaceAfter=No
13      .       _       _       _       _       _       _       _       NER=O
```

**Comment by nljubesi** [comment]
@lkrsnik Could you maybe deal with this in the following days / weeks? It should be very simple. Once the NER labels are in, you should iterate through these and change each `I-X` label into `B-X` if there was not a `B-X` label beforehand. Discontinued labels are allowed, so `B-ORG O O I-ORG` is valid, but `I-ORG O O I-ORG` is not. In the above example, the label of `dom`should change from `I-ORG` to `B-ORG`.

**Comment by TomazErjavec** [comment]
@lkrsnik, @nljubesi, could you bump this issue. I just had problems again with this bug and it is rather frustrating.

**Comment by nljubesi** [comment]
I thought @lkrsnik solved this. Might not be the case. I am waiting for @lkrsnik to deal with the lexicon building issues that are crucial for training RSDO models, I hope he will be able to deal with this (and some other issues) right after the big lexicon building issue is resolved.
