### ISSUE TITLE
Error running 'import classla': UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 664: character maps to <undefined>

### ISSUE THREAD

**Issue by ebouna** [clarinsi/classla-stanfordnlp#14]
I successfully installed classla on a windows system (running `pip install classla` in the terminal). However, on running `import classla` in python, I keep getting the error `UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 664: character maps to <undefined>`.
Thanks in advance for any hints/ pointers.

**Comment by nljubesi** [comment]
Thank you, @ebouna, for reporting this issue. The issue lies in a tool that is included with classla (obeliks tokenizer for Slovenian) that was obviously not tested on Windows yet. We are working on resolving the obeliks issue and will report here once everything is as it should be.

Thank you once again!

**Comment by ebouna** [comment]
Thank you very much, @nljubesi, for your answer and for your help!

**Comment by lkrsnik** [comment]
Underlying tool was upgraded. Since you already installed old version together with classla, you have to upgrade it manually. Simply write:
`pip install obeliks --upgrade`

Please let us know if this solves your issue.

**Comment by ebouna** [comment]
Many thanks for your help! Everything works fine. This seems to solve the problem. Your tool is great.

**Comment by nljubesi** [comment]
Thanks, feel free to share how you use the tool. Once you share this (you do not have to, of course), you can close the issue.

And thank you for reporting the issue!

**Comment by ebouna** [comment]
Thanks a lot again, @nljubesi! Thanks for your immediate help. Sorry, I did not know I had to close the issue. I'll do that right now.
