### ISSUE TITLE
Basic text clean-up prior to processing

### ISSUE THREAD

**Issue by nljubesi** [clarinsi/classla-stanfordnlp#15]
I am regularly getting negative feedback on noise in the processed text. That noise was present in the text from before, so this is not a classla issue per se, but there is room for a classla feature.

I am documenting here what should be done:
- NO-BREAK SPACE (U+00A0) to standard space (U+0020)
- NON-BREAKING HYPHEN (U+2011) to standard hyphen character (U+002D)
- SOFT HYPHEN (U+00AD) deleted
- decomposition of composed characters, quite probably with python's unicodedata.normalize(form, unistr), the form being "NFC" (@TomazErjavec, did I get this right?)

I will produce a function performing these normalizations and then discuss, quite probably with @lkrsnik on how to implement this normalization as a default? feature in the classla process.

**Comment by TomazErjavec** [comment]
> decomposition of composed characters, quite probably with python's unicodedata.normalize(form, unistr), the form being "NFC" (@TomazErjavec, did I get this right?)

NFC (Canonical Decomposition, followed by Canonical Composition) is the safe way to do it, although NFKC (Compatibility Decomposition, followed by Canonical Composition) might be ok - or even beter! - for text processing. The difference is that NFC totaly preserves information, but NFKC does not always, e.g. ⁹ becomes 9 (cf. http://unicode.org/reports/tr15/) , but this would be an advantage if the tagger etc doesn't know what to do with ⁹.

But great that you will include this text-cleaning feature, it will get rid of lots of problems that I noticed.
