### ISSUE TITLE
Croatian & Serbian (stand. & nonstand.) models mistag and mislemmatize aorist and imperfect

### ISSUE THREAD

**Issue by ebouna** [clarinsi/classla-stanfordnlp#16]
Trying out classla for Croatian & Serbian (stand. & nonstand.), I have seen that the tool yields excellent results in tagging and lemmatizing. However, unfortunately, there seems to be one exception: aorist and imperfect forms. 
I tested, e.g., text passages such as `Otkako znam za se, sve mi nekako bješe najstarija pomisao i srce mi se po njoj otimaše.` or `Nakon časa i po vožnje, izgubismo iz vida more, a u isti mah počesmo se spuštati u dolu, u kojoj se nalazi seoce Mirac. Tu nas dočekaše prve pahuljice snijega.`

I may add here that I would really like to use classla for adding POS tags and lemmatization results to a 20th c. text corpus I am currently analysing. The corpus consists of Croatian novels from the 1st half of the 20th c. and contains many aorists and imperfects. The issue described above, however, makes the use of the present models rather problematic as it appears to me right now.

Is there a way for me to fix this problem quite easily (since I really need the tagging/lemmatizing)?   Or could the problem be solved perhaps for the application in general? Thanks a lot once again for your help.

**Comment by nljubesi** [comment]
Interesting problem you have! There is a very simple reason for this - aorist and imperfect forms were not seen either in Croatian or Serbian training data.

The solution is to add to the training data sentences with aorist and imperfect. I see two solutions:

1. You take a sample of sentences with aorist and imperfect, where you correct the annotation of these tenses (and check that the remaining tokens are correctly annotated).
2. We synthesize some data from current training data, given that we do have aorist and imperfect forms in the inflectional lexicons (http://hdl.handle.net/11356/1232 and http://hdl.handle.net/11356/1233).

I am much more in favour of the first option as the second one might produce weird constructions. Are you able to produce automatic POS annotation only of a sample of sentences (a few tens of sentences should suffice), with aorist and imperfect annotations corrected, and other annotations quickly validated? The conllu format sounds just right for this task. I would then retrain the models with these sentences added to the training data.

**Comment by ebouna** [comment]
I have started to collect sentences with aorist and imperfect, in order to help realize solution 1. Please find attached a first example, in which I checked and corrected the first 5 columns of each token.

[sentence1_Vma1s.txt](https://github.com/clarinsi/classla/files/6373101/sentence1_Vma1s.txt)

Unfortunately, I had a number of issues when I tried to convert from the conll-u format to a python object and vice versa using classla. But I will have to ask about them in separate threads.

**Comment by nljubesi** [comment]
By first five columns you consider columns 2-6, so including the FEATS column?

This looks good, I guess you are aware of the XPOS->UPOS+FEATS mapping at https://github.com/nljubesi/hr500k/blob/master/mte5-udv2.mapping?

For the classla objects, yes, they are rather spotty (taken over from stanza), it would be good if you documented the issue, but I guess here you can just output conllu and manually  correct columns 3, 4, 5, 6? Previously I mentioned you should correct only part-of-speech information, but, yes, lemma should be adapted as well.

**Comment by ebouna** [comment]
Yes, exactly: I checked the columns 3,4,5,6 . (Sorry, when I mentioned I had corrected "the first 5 columns", that was imprecise.) Thanks a lot in addition for pointing out [https://github.com/nljubesi/hr500k/blob/master/mte5-udv2.mapping](url), a page I was not aware of. I had used [http://nlp.ffzg.hr/data/tagging/msd-hr.html](url), which, however, sometimes differs from [https://github.com/nljubesi/hr500k/blob/master/mte5-udv2.mapping](url).

**Comment by nljubesi** [comment]
Uff, the http://nlp.ffzg.hr/data/tagging/msd-hr.html is a super-old specification. You should use https://github.com/nljubesi/hr500k/blob/master/mte5-udv2.mapping, if this is informative enough for you. Here you also have the mapping from XPOS to UPOS+FEATS, which is relevant as well.

The current MULTEXT-East specifications are these: http://nl.ijs.si/ME/V6/msd/html/msd-hbs.html.
