### ISSUE TITLE
Long sentences obtain <PAD> deprel

### ISSUE THREAD

**Issue by nljubesi** [clarinsi/classla-stanfordnlp#17]
**Describe the bug**
When I process long Wikipedia sentences, I get `<PAD>` as the predicted deprel.

**To Reproduce**
```
import classla
nlp = classla.Pipeline('sr')
text='Njegove kratke priče i pesme objavljivane su u crnogorskoj nevladinoj kulturnoj organizaciji "Fenomeni” iz Kolašina; u Srbiji je štampan u književnom zborniku iz Bajine Bašte "Kiprijanov kladenac” u izdanju iz 2016. i 2019. godine; u 41. broju književnog zbornika za mlade sa prostora Eks-Jugoslavije "Rukopisi" koji objavljuje "Dom omladine Pančevo" u izdanju iz 2018. godine; u 521. broju novosadskog časopisa "Polja"; u 36. i 37. broju "Balkanskog književnog glasnika" i na književnim internet-portalima "Hiperboreja" i "Libela"; u Bosni i Hercegovini je zastupljen na kulturnim portalima "Astronaut”, "Nomad", kao i na mostarskom portalu za književnost i kulturu "Strane", takođe njegova poezija zastupljena je na sajtu "PEN centra BiH" kao i na sajtu "Hipomnemata" koji uređuje pesnik i dramaturg Darko Cvijetić iz Prijedora; u Hrvatskoj ga je objavila i štampala izdavačka kuća "Durio” iz Zagreba u svom književnom časopisu "Fantom Slobode” u prolećnim brojevima za 2017. i 2018. godinu, njegova poezija štampana je u književnom magazinu "Preporodov Žurnal" koji izlazi u Zagrebu; njegova kratka priča "Prodavac ploča kod katedrale" štampana je u zagrebačkom književnom magazinu "Bestbuk", takođe je zastupljen na književnim internet-portalima "Kritična masa", "Metafora" i "Radio Gornji Grad" a njegove pesme i priče redovno objavljuje književnik Miljenko Jergović na svom sajtu u rubrici "Ajfelov most"; na Kosovu i Metohiji njegova je poezija prevedena na albanski jezik i objavljena na onlajn kulturnom portalu "Kultplus” sa sedištem u Prištini, na sajtu "Fonda za Kulturnu Edukaciju i Nasleđe- FEKT" sa sedištem u Orahovcu, kao i u nezavisnoj medijskoj organizaciji "Kosovo 2.0" koja dela kroz štampani i onlajn časopis sa sedištem u Prištini; u Makedoniji je objavljen u 119. broju časopisa "Blesok" iz Skoplja u prevodu na makedonski i engleski jezik.'
doc = nlp(text)
doc.sentences[0].print_dependencies()
```

**Expected behavior**
There should be no `<PAD>` deprels.

**Comment by nljubesi** [comment]
Luka had a look and he realised that these predictions come as bad predictions due to the sentence length and the available `<PAD>` token used for padding.

@kajad we suggest Luka replaces these `<PAD>` dependency relations with any deprel that is general enough and that should not hurt any downstream analyses. We were thinking of the `punct` deprel. You might have another idea. The predictions in these very long sentences are very wrong anyway, so there would be no reasonable way for us to retrieve good predictions. Idea is just to output something that 1. will validate and 2.  will not hurt potential analyses or extractions in any nasty way.

**Comment by kajad** [comment]
I suggest using the 'dep' label (https://universaldependencies.org/u/dep/dep.html). How about parent ID, is there any particular HEAD number assigned to `<PAD>`?

**Comment by nljubesi** [comment]
All instances have heads. Overall the parsing results in such sentences are rubbish. For the example sentence above, this is the start of the output:

```
('Njegove', 3, 'vocative')
('kratke', 3, 'vocative')
('priče', 22, 'iobj')
('i', 5, 'vocative')
('pesme', 3, 'vocative')
('objavljivane', 22, '<PAD>')
('su', 6, '<PAD>')
('u', 12, 'case')
('crnogorskoj', 12, 'amod')
('nevladinoj', 12, 'amod')
('kulturnoj', 12, 'amod')
('organizaciji', 22, 'dep')
('"', 14, 'punct')
```

`dep` sounds great, exactly what we were after. We do not think such long sentences should be parsed at all as the output is bad, but we at least want make sure that the output is well-formatted. Taking anything from the head, as you can see, would not make more sense than `dep`.

For handling too long sentences and parsing, we currently have two suggestions:
- make the tokenizer split sentences not later than N(=100?) tokens
- enable for the parser not to parse sentences longer than N(=100?) tokens

We would not mind hearing your opinion on the two presented options, @kajad!

**Comment by kajad** [comment]
Alas, none of the two options is ideal - modifying the stand-alone tokenizer to meet the limitations of a particular tool is somewhat artificial, whereas leaving some sentences unparsed would definitely lead to issues in validations, corpus statistics, etc. Is there any particular reason to not use the original PAD=dep solution with extra long sentences? Does it cause the tool to break or slow down significantly? 

Discussion aside - if we have to go for one of the two options, I vote for the first one.

**Comment by simonkrek** [comment]
I agree with Kaja.
> Discussion aside - if we have to go for one of the two options, I vote for the first one.

**Comment by lkrsnik** [comment]
As suggested, 'dep' label is now used to replace <PAD>. I am leaving this issue open, since we might work on it further in the future.
