### ISSUE TITLE
[QUESTION] Classla working from linux shell and on windows local host but not with hosting

### ISSUE THREAD

**Issue by nedimdzanic** [clarinsi/classla-stanfordnlp#18]
Hello,
I have steange problem with classla that occurred yesterday.
I have tested everything on my localhost on windows machine and it was working just fine, but
when I transferred everything on public host classla module was not working as expected.
Host is running on Linux Debian 10 x64, PHP v7.4, Python 3.9, pip 21.1, Nginx 1.18.
When I try running it from the Linux shell using python/php command output is same as on windows machine and there 
is no any problems with that, however if I try to access the same php script using my browser, something goes wrong and
there is no output at all.
I am assuming that Nginx needs some adjustments for classla since Nginx is able to load/execute python scripts, 
it even loads classla (import classla) but it stucks at "classla.download('hr')"
So I am wondering if anyone has the same problem and what is possible solution, and are there any extra requirements 
for the linux nginx. 
Thanks in advice!

**Comment by nljubesi** [comment]
Hey, I guess you can download the models prior to running classla through the web server. There is no need to download the models again by the web server. Hope I understood your issue.

**Comment by nedimdzanic** [comment]
Now stuck at "nlp = classla.Pipeline('hr')" or any other code related to classla.

**Comment by nedimdzanic** [comment]
> Hey, I guess you can download the models prior to running classla through the web server. There is no need to download the models again by the web server. Hope I understood your issue.

Now stuck at "nlp = classla.Pipeline('hr')" or any other code related to classla.

**Comment by nljubesi** [comment]
I cannot debug your situation from here, but I wonder whether your setup is making sense in the first place.

If you want to use classla in the background for your web app, I guess you do not want to load classla models each time a new http request arrives, but want to have a service in the back, serving the requests obtained via http.

classla has a server feature (thanks to it being based on stanza), so you could explore that: https://stanfordnlp.github.io/stanza/client_properties.html. This feature was not tested yet on classla, so no idea how easy this is to set up. Or you can use the old ReLDI web service if this is easier (you requested access, right?).
