### ISSUE TITLE
Creating a non-standard language pipeline loads standard language models

### ISSUE THREAD

**Issue by nljubesi** [clarinsi/classla-stanfordnlp#2]
If I do not download non-standard language models `classla.download('sr',type='nonstandard')`, the standard models are used.
`
>>> nlp=classla.Pipeline('sr',type="nonstandard")
Use device: gpu

Loading: tokenize
With settings: 
{'model_path': '/home/nikolal/classla_resources/sr_set_models/sr_set_tokenizer.pt', 'lang': 'sr', 'shorthand': 'sr_nonstandard', 'mode': 'predict', 'type': 'nonstandard'}

Loading: ner
With settings: 
{'model_path': '/home/nikolal/classla_resources/sr_set_models/sr_set_ner.pt', 'pretrain_path': '/home/nikolal/classla_resources/sr_set_models/sr_set.pretrain.pt', 'forward_charlm_path': None, 'backward_charlm_path': None, 'lang': 'sr', 'shorthand': 'sr_nonstandard', 'mode': 'predict', 'type': 'nonstandard'}

Loading: pos
With settings: 
{'model_path': '/home/nikolal/classla_resources/sr_set_models/sr_set_tagger.pt', 'pretrain_path': '/home/nikolal/classla_resources/sr_set_models/sr_set.pretrain.pt', 'lang': 'sr', 'shorthand': 'sr_nonstandard', 'mode': 'predict', 'type': 'nonstandard'}

Loading: lemma
With settings: 
{'model_path': '/home/nikolal/classla_resources/sr_set_models/sr_set_lemmatizer.pt', 'lang': 'sr', 'shorthand': 'sr_nonstandard', 'mode': 'predict', 'type': 'nonstandard'}
Building an attentional Seq2Seq model...
Using a Bi-LSTM encoder
Using soft attention for LSTM.
Using POS in encoder
Finetune all embeddings.
[Running seq2seq lemmatizer with edit classifier]

Loading: depparse
With settings: 
{'model_path': '/home/nikolal/classla_resources/sr_set_models/sr_set_parser.pt', 'pretrain_path': '/home/nikolal/classla_resources/sr_set_models/sr_set.pretrain.pt', 'lang': 'sr', 'shorthand': 'sr_nonstandard', 'mode': 'predict', 'type': 'nonstandard'}
Done loading processors!
`

**Comment by lkrsnik** [comment]
This should be fixed with commit a216e2bf45f27d31b938c65fb26d2b2f4c9cea2e.
