### ISSUE TITLE
Bug with lemmatisation of Slovene words with hyphens

### ISSUE THREAD

**Issue by TomazErjavec** [clarinsi/classla-stanfordnlp#21]
As also described on [ParlaMint issues](https://github.com/clarin-eric/ParlaMint/issues/102) most words that contain hyphens get wrongly lemmatised with - at least - the hyphen exchanged for some letter, and the rest of the word often mangled as well, e.g. 500-metrskimi /5t0emetrski, dnevno-varstveni /dnevnosvarstven, le-tega /lest, prostorsko-gradbeno /prostorskongradben, 27,5-odstotno /2vzfsodstoten, 80-odstotna /c0vodstoten.

It seems that this bug affects only Slovene, e.g. Croatian is [ok](https://www.clarin.si/noske/parlamint21.cgi/first?corpname=parlamint21_hr&reload=&iquery=&queryselector=cqlrow&lemma=&phrase=&word=&char=&cql=%22.%2B-....%2B%22&default_attr=word&fc_lemword_window_type=both&fc_lemword_wsize=5&fc_lemword=&fc_lemword_type=all&fsca_speech.session=&fsca_speech.speaker_name=&fsca_speech.speaker_birth=). As far as I could tell, Bulgarian is also [ok](https://www.clarin.si/noske/parlamint21.cgi/first?corpname=parlamint21_bg&reload=&iquery=&queryselector=cqlrow&lemma=&phrase=&word=&char=&cql=%22.%2B-....%2B%22&default_attr=word&fc_lemword_window_type=both&fc_lemword_wsize=5&fc_lemword=&fc_lemword_type=all&fsca_speech.session=&fsca_speech.speaker_name=&fsca_speech.speaker_birth=).

**Comment by nljubesi** [comment]
I gave the reasons for this bug on the ParlaMint side. If anyone thinks that something constructive could be done on the side of classla, please speak up. To me, this is a training data issue.

**Comment by nljubesi** [comment]
This is not an issue any more in classla 1.1.0.
