### ISSUE TITLE
Value error from reldi tokeniser.

### ISSUE THREAD

**Issue by bkolosk1** [clarinsi/classla-stanfordnlp#23]
**Describe the bug**
While running the reldi_toneiser on UNIX, I experienced the following error: 

```
web_1  |   File "/usr/local/lib/python3.8/site-packages/classla/pipeline/core.py", line 112, in __init__
web_1  |     self.processors[processor_name] = NAME_TO_PROCESSOR_CLASS[processor_name](config=curr_processor_config,
web_1  |   File "/usr/local/lib/python3.8/site-packages/classla/pipeline/processor.py", line 146, in __init__
web_1  |     self._set_up_model(config, use_gpu)
web_1  |   File "/usr/local/lib/python3.8/site-packages/classla/pipeline/tokenize_processor.py", line 32, in _set_up_model
web_1  |     self._tokenizer = ObeliksTrainer(config.get('lang'), config.get('type'))
web_1  |   File "/usr/local/lib/python3.8/site-packages/classla/utils/obeliks.py", line 32, in __init__
web_1  |     from classla.submodules.reldi_tokeniser import tokeniser
web_1  |   File "/usr/local/lib/python3.8/site-packages/classla/submodules/reldi_tokeniser/tokeniser.py", line 13, in <module>
web_1  |     signal(SIGPIPE, SIG_DFL)
web_1  |   File "/usr/local/lib/python3.8/signal.py", line 47, in signal
web_1  |     handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
web_1  | ValueError: signal only works in main thread
```

**To Reproduce**
1. This happens if you call the reldi_tokeniser in a Flask APP

**Expected behavior**
To tokenize the words without any issues.

**Proposed solution**
- After looking arround I found that you had the same bug and you fixed it in another repo:
 https://github.com/clarinsi/reldi-tokeniser/commit/e34b59e2f8365cd25e7194512eda76809c878f1d
- I used the same approach in the original site-package and it worked.
- I Saw that you haven't linked the latest code from the original RELDI-TOKENISER REPO https://github.com/clarinsi/classla/tree/master/classla/submodules
- I propose you to link the latest **repo** to the classla/submodules/reldi-tokeniser

**Comment by nljubesi** [comment]
This issue will be resolved with the new version that will use an external reldi-tokeniser with added object support.

**Comment by lkrsnik** [comment]
As of latest classla version (1.1.0), reldi-tokeniser stopped being included as a GitHub submodule, but as an external library (https://pypi.org/project/reldi-tokeniser/).

Thank you!
