### ISSUE TITLE
Fails to recognize foreign phrase

### ISSUE THREAD

**Issue by mihabogataj** [clarinsi/classla-stanfordnlp#27]
Firstly I'd like to say that the system works excellent most of the time! However I came across an issue in Slovene sentence when classla failed to recognize foreign sequence.

The issue appears in following sentence:
"Res je, rezultat trdega dela je sedaj nasmejani Cameron, ki je letošnji zmagovalec na avstralskem Men`s Healthovem FITNES IZZIVU."

It fails to recognize that "Men's Health" is not Slovene, which returns for the word Men as "Jaz" in first person singular locative. I can provide any other information you request from me.

The version of Classla that I use is 1.0.2.

I understand this may be a very extreme case where even the foreign word is conjugated.

**Comment by nljubesi** [comment]
Thank you for your kind words, as well as the interesting issue. There are actually two issues in your example that classla is not dealing with properly, and they are connected.

One is the rather non-standard apostrophe ```````, another is the partially foreign phrase. You are probably using the non-standard mode of the Slovenian models, and you can understand the urge of the tagger to go for `men` with the `meni` hypothesis. If ```men`s``` was kept together, this would have been different (```PROPN	Npmsl```, which is rather correct).

If @simonkrek thinks that ```Men`s Healthovem``` should be kept as two tokens, the obeliks and the reldi-tokeniser tokenizers will have to be updated.

**Comment by mihabogataj** [comment]
That is correct, I am using non-standard model.
