### ISSUE TITLE
Problem with sentence segmentation for CoNLLU computation

### ISSUE THREAD

**Issue by mrspock434** [clarinsi/classla-stanfordnlp#28]
**Description**

Sentence segmentation is performing poorly. Longer sequences of text are joined and segmented as sentences improperly. Maybe a result of improper tokenization? 

**To Reproduce**

1. Compute CoNLLU's for following document enclosed in testcase.zip (2660.txt)
2. Observe the result (2660.plainText.conllu)

Testcase input and output: [testcase.zip](https://github.com/clarinsi/classla/files/7912528/testcase.zip)

**Comment by nljubesi** [comment]
We are dealing with this issue offline. If anything is to be reported here, we will reopen.
