### ISSUE TITLE
Cannot import classla on Windows

### ISSUE THREAD

**Issue by tjasaje** [clarinsi/classla-stanfordnlp#29]
Classla (version 1.1.0) cannot be imported on a Windows system due to an UnicodeDecodeError:

![classlaImportError](https://user-images.githubusercontent.com/79084005/150944077-2c7f2f6f-f6c5-4499-ad5b-ff995779da9f.png)
.

**Comment by nljubesi** [comment]
Thank you for reporting this @tjasaje.

@lkrsnik, is this due to Windows default CP1250 encoding (ah)? Should reldi-tokeniser be updated with open(encoding="utf-8")? If so, please do that (I cannot currently push to pip, we will have to change this).

**Comment by lkrsnik** [comment]
Yes, the issue was in reldi-tokeniser. To fix this, please upgrade reldi-tokeniser in your environment, using:

```
pip install reldi-tokeniser --upgrade
```
