### ISSUE TITLE
Text attribute of the sentence object is unreliable

### ISSUE THREAD

**Issue by sharpsy** [clarinsi/classla-stanfordnlp#34]
**Describe the bug**
Text attribute of the sentence object (added in #32) does not contain correct information when the control characters are present in the string.

**To Reproduce**
```
import classla, stanza

testcase_sentence = "France Prešeren je rojen v Vrbi. \f France Prešeren danes velja za največjega slovenskega pesnika."

st_nlp = stanza.Pipeline(lang="sl", processors="tokenize")
cl_nlp = classla.Pipeline(lang="sl", processors="tokenize")
stanza_result = st_nlp(testcase_sentence)
classla_result = cl_nlp(testcase_sentence)
print(stanza_result.sentences[0].text)  # prints text as expected
print(stanza_result.sentences[1].text)  # prints text as expected
print(classla_result.sentences[0].text)  # prints text as expected
print(classla_result.sentences[1].text)  # whoops
# Please note that the tokens from the 2nd sentence are correctly detected. The text attribute is at odds with the detected text of words.
assert [w.text for w in stanza_result.sentences[1].words] == [w.text for w in classla_result.sentences[1].words]
```

**Expected behavior**
I would expect that a text attribute of a sentence object matches the span of the input text where the tokenized words originated from.

**Environment (please complete the following information):**
    OS: Fedora 35
    Python version: Python 3.10.7
    Stanza version: 1.4.0
    Classla version: 1.2.0

**Comment by nljubesi** [comment]
Thank you, @sharpsy for reporting this! We seem never to test our solutions with enough rigor, so great to have you out there.

@lkrsnik, please resolve the issue at your earliest convenience. @simonkrek fyi.
