### ISSUE TITLE
CLI lemmatization code for Slovenian not working

### ISSUE THREAD

**Issue by nljubesi** [clarinsi/classla-stanfordnlp#35]
**Describe the bug**

After having a model for lemmatization trained in `classla-spoken/models/lemma/baseline.pt`, running the usual code for predicting with the model

```
python -m classla.models.lemmatizer --model_dir classla-spoken/models/lemma/ --model_file baseline --eval_file classla-spoken/out/sst-test.baseline.pos.conllu --output_file classla-spoken/out/sst-test.baseline.pos.lemma.conllu --gold_file classla-spoken/conllu/sst-test.conllu --mode predict
```

returns 

```
Running lemmatizer in predict mode
Traceback (most recent call last):
  File "/home/nikolal/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/nikolal/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nikolal/tools/classla/classla/models/lemmatizer.py", line 314, in <module>
    main()
  File "/home/nikolal/tools/classla/classla/models/lemmatizer.py", line 105, in main
    evaluate(args)
  File "/home/nikolal/tools/classla/classla/models/lemmatizer.py", line 250, in evaluate
    trainer = Trainer(model_file=model_file, use_cuda=use_cuda)
  File "/home/nikolal/tools/classla/classla/models/lemma/trainer.py", line 37, in __init__
    self.load(model_file, use_cuda)
  File "/home/nikolal/tools/classla/classla/models/lemma/trainer.py", line 230, in load
    self.word_dict, self.composite_dict = checkpoint['dicts']
KeyError: 'dicts'
```

so it seems that the model checkpoint does not have the `dicts` key, which is quite likely related with the change in Slovenian where the dictionary is saved in the pos model. My guess would be that using the `--pos_model_path classla-spoken/models/pos/baseline` should be used, to let the lemmatizer know where it can find the lexicon inside the pos model, but this seems not to have been implemented yet.

Please inspect this @lkrsnik at your earliest convenience because a project deadline (slokit) depends on this bug resolution. cc @simonkrek @kajad

**Comment by nljubesi** [comment]
I am extending this issue with the info that CLI lemmatization also does not work for the remaining languages.

```
$ python -m classla.models.lemmatizer --model_dir models/lemma/ --model_file hr_all_hrLex_lemmatizer --eval_file data/pos.hr500k.dev.conllu --output_file temp --gold_file data/pos.hr500k.dev.conllu --mode predict
```

results in 

```
Running lemmatizer in predict mode
2022-10-26 08:56:12 DEBUG: Building an attentional Seq2Seq model...
2022-10-26 08:56:12 DEBUG: Using a Bi-LSTM encoder
2022-10-26 08:56:12 DEBUG: Using soft attention for LSTM.
2022-10-26 08:56:12 DEBUG: Using POS in encoder
2022-10-26 08:56:14 DEBUG: Finetune all embeddings.
2022-10-26 08:56:14 DEBUG: Running seq2seq lemmatizer with edit classifier...
Traceback (most recent call last):
  File "/home/nikolal/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/nikolal/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nikolal/tools/classla-stanfordnlp/classla/models/lemmatizer.py", line 321, in <module>
    main()
  File "/home/nikolal/tools/classla-stanfordnlp/classla/models/lemmatizer.py", line 99, in main
    evaluate(args)
  File "/home/nikolal/tools/classla-stanfordnlp/classla/models/lemmatizer.py", line 251, in evaluate
    trainer = Trainer(model_file=model_file, use_cuda=use_cuda)
  File "/home/nikolal/tools/classla-stanfordnlp/classla/models/lemma/trainer.py", line 64, in __init__
    self.pos_lemma_pretag = args['pos_lemma_pretag'] if 'lemma_pretag' in args else None
TypeError: argument of type 'NoneType' is not iterable
```

It seems that in the last patch-up of the CLI tools we, @lkrsnik, focused only on the training, while the prediction mode requires similar interventions as did the training mode.

I guess the most sensible approach is to resolve issues in the script for both types of models (lexicon in tagger model, and lexicon in lemmatizer) at once, but if time is scarce right now, resolving the Slovenian problem might work for the next few weeks.

Also, what I think is smart, adding the prediction mode in the `tests_classla/test_lemmatizer.py` script.

**Comment by lkrsnik** [comment]
The problem indeed was that prediction mode was not updated. I created a quick fix, but was unable to test it on your example, since you haven't provided required models. Please pull the latest commit and test it out. For better results, you should use `--pos_model_path`. If it still won't load, you should force it via `--pos_force_inf_lexicon`.

**Comment by nljubesi** [comment]
I am still getting the same errors as before. After some digging, I realised that my newly trained lemmatization models lack the `dicts` key in the model which are, at least in the Slovenian models from clarin.si, actually lists of two empty dictionaries. This is, I guess, because the lexicon from the pos model is used. After adding this `[{},{}]` to the newly trained model, the predictions run with, I can only assume, reasonable outputs.

I guess that this means that the lemmatization training does not construct the fake empty `dicts` keys. Can you update the lemmatization training so that the output models can be used in prediction? Do you consider the code overall to be stable enough so that experiments that I am running make sense?

Beyond this, I have the feeling that there are blind spots in this code. I do not fully understand the need for `--pos_force_inf_lexicon`, it feels like the code is not super-stable, but we can discuss this when you are more free.

**Comment by nljubesi** [comment]
Ah yes, if you want to have a look at a newly trained lemmatization model, one is available from https://github.com/clarinsi/classla-spoken/blob/main/models/lemma/baseline_lemmatizer.pt.

**Comment by lkrsnik** [comment]
> I guess that this means that the lemmatization training does not construct the fake empty `dicts` keys. Can you update the lemmatization training so that the output models can be used in prediction?

I updated evaluation code in a way that if `dict` keys don't exist, it automatically sets self.word_dict and self.composite_dict to {} (pull latest commit). This seems to have fixed your problem and you won't have to retrain your models.

> Do you consider the code overall to be stable enough so that experiments that I am running make sense?

If you already have POS annotated and handchecked then these experimets do make sense. Code should be stable enough since it is ran by classla itself. As for `--pos_force_inf_lexicon` - I only added it in last commit, to make sure your code would run as it should, because I didn't see into your model. Now that I have seen it, I can tell that it is redundant and will remove it in next commit.

**Comment by nljubesi** [comment]
> > I guess that this means that the lemmatization training does not construct the fake empty `dicts` keys. Can you update the lemmatization training so that the output models can be used in prediction?
> 
> I updated evaluation code in a way that if `dict` keys don't exist, it automatically sets self.word_dict and self.composite_dict to {} (pull latest commit). This seems to have fixed your problem and you won't have to retrain your models.

That is true. Great.

> > Do you consider the code overall to be stable enough so that experiments that I am running make sense?
> 
> If you already have POS annotated and handchecked then these experimets do make sense. Code should be stable enough since it is ran by classla itself. As for `--pos_force_inf_lexicon` - I only added it in last commit, to make sure your code would run as it should, because I didn't see into your model. Now that I have seen it, I can tell that it is redundant and will remove it in next commit.

Aha, ok, now I understand, this was just an additional precaution because you did not have insight in my model (which points towards the lack of control of what the lemmatizer training script is doing).

For now I can continue, thanks, it still seems that this training and prediction procedure requires some attention to iron out potential wrinkles. Leaving this open, also to assure that the newly introduced `--pos_force_inf_lexicon` is removed.

**Comment by nljubesi** [comment]
And with the current patch-up it seems that the official non-standard lemmatization model cannot be used with the lexicon from the official non-standard pos-tagging model.

```
$ python -m classla.models.lemmatizer --model_dir classla-spoken/models/lemma/ --model_file classla_nonstandard --eval_file classla-spoken/out/sst-test.classla_nonstandard.pos.conllu --output_file classla-spoken/out/sst-test.classla_nonstandard.pos.lemma.conllu --gold_file classla-spoken/conllu/sst-test.conllu --pos_model_path classla-spoken/models/pos/classla_nonstandard --mode predict

Running lemmatizer in predict mode
2022-10-27 11:29:39 DEBUG: Building an attentional Seq2Seq model...
2022-10-27 11:29:39 DEBUG: Using a Bi-LSTM encoder
2022-10-27 11:29:39 DEBUG: Using soft attention for LSTM.
2022-10-27 11:29:39 DEBUG: Using POS in encoder
2022-10-27 11:29:42 DEBUG: Finetune all embeddings.
2022-10-27 11:29:42 DEBUG: Running seq2seq lemmatizer with edit classifier...
Traceback (most recent call last):
  File "/home/nikolal/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/nikolal/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nikolal/tools/classla/classla/models/lemmatizer.py", line 317, in <module>
    main()
  File "/home/nikolal/tools/classla/classla/models/lemmatizer.py", line 106, in main
    evaluate(args)
  File "/home/nikolal/tools/classla/classla/models/lemmatizer.py", line 251, in evaluate
    trainer = Trainer(args=args, model_file=model_file, use_cuda=use_cuda)
  File "/home/nikolal/tools/classla/classla/models/lemma/trainer.py", line 62, in __init__
    self.composite_dict = PosTrainer.load_influectial_lexicon(args['pos_model_path'])
  File "/home/nikolal/tools/classla/classla/models/pos/trainer.py", line 162, in load_influectial_lexicon
    for entry in checkpoint['dicts']:
KeyError: 'dicts'
```

Rather obvious things have to be ironed out with enough time on our hands.
