### ISSUE TITLE
Outdated resources.json for nonstandard Slovenian

### ISSUE THREAD

**Issue by lkrsnik** [clarinsi/classla-stanfordnlp#40]
**Describe the bug**
I noticed that you uploaded new nonstandard model for Slovenian (https://www.clarin.si/repository/xmlui/handle/11356/1786), but by the looks of it classla still uses the old one (https://www.clarin.si/repository/xmlui/handle/11356/1337).

**To Reproduce**
Check out latest resources file, line 303 - https://github.com/clarinsi/classla-resources/blob/main/resources_2.1.json#L303C18-L303C28

**Expected behavior**
Classla should use new models?

**Comment by nljubesi** [comment]
Resolved, thanks.
