### ISSUE TITLE
Problems with classla.Pipeline()

### ISSUE THREAD

**Issue by tjasaje** [clarinsi/classla-stanfordnlp#44]
**Describe the bug**
Cannot set Pipeline.

**To Reproduce**
>>> import classla
>>> nlp=classla.Pipeline()

![image](https://github.com/clarinsi/classla/assets/79084005/7a48f99a-7f8e-49cc-82be-35092471cc1b)

**Environment (please complete the following information):**
 - OS: Windows, MacOS
 - Python version: 3.9

**Comment by nljubesi** [comment]
You are supposed to define at least the language in the Pipeline() constructor, like Pipeline('hr'). Closing.
