### ISSUE TITLE
Problem installing classla on Python version 3.12

### ISSUE THREAD

**Issue by 0sebek** [clarinsi/classla-stanfordnlp#45]
**Describe the bug**
I tried to port my Python to the latest release version 3.12. After trying to install classla, I came to the error ModuleNotFoundError: No module named 'distutils'. After some digging, I found out Python no longer includes distutils module. 

**To Reproduce**
1. Run pip install classla on fresh installation of Python 3.12.1

**Expected behavior**
Classla should install successfuly

**Environment (please complete the following information):**
 - OS: Windows 11
 - Python version: Python 3.12.1
 - Stanza version: Latest

**Comment by nljubesi** [comment]
Thanks for reporting this! We are currently supporting python 3.6, 3.7 and 3.8. At some point we will want to look into newer versions, and your report will be handy then.
