### ISSUE TITLE
Croatian, Serbian and Bulgarian standard models mistag quotes

### ISSUE THREAD

**Issue by nljubesi** [clarinsi/classla-stanfordnlp#5]
The sentence

<pre>Tako i srpski „trpi“ „okupaciju“ od strane engleskog jezika kao lingua franca.</pre>

alarmed us that a good part of the models has not seen, neither in the training data, nor in the embeddings, alternative quotes. With the Serbian standard model the above quotes are tagged as nouns and adjectives. With the non-standard model the tags are correct. The Bulgarian model tags one of the quotes correctly, for the other it assumes to be a residual. The Croatian standard model correctly tags one of the quotes, while the other is tagged as an adjective or a noun. The non-standard model, again, preforms well. In Slovene the tags seem ok.

One potential approach might be to extend the tagger with a list of punctuations and enforce those. TBD.

**Comment by vukbatanovic** [comment]
I'm not sure the Slovene model is entirely free of errors of this sort, for instance in the following example the first quote is tagged as Xf by the non-standard model:
`Ja kak pa si naj jas zaj tou tolmačin? Je touti vaš „conditio sine qua non“ en nouvi müster za “funkcioniranja” v najbuj modično pokakani Prleččini al kaj?`

**Comment by lkrsnik** [comment]
Such strings now get tagged by tokenizers (reldi and obeliks).
