### ISSUE TITLE
support for torch1.7

### ISSUE THREAD

**Issue by ninoslavc** [clarinsi/classla-stanfordnlp#6]
classla 0.0.10 relies on torch 1.5. Is it possible to support the current version 1.7?

**Comment by nljubesi** [comment]
We might start support it once we catch up with the developments in Stanza (will work on this in the following month). Could you document here your issue while using torch version 1.7? Thanks!

**Comment by nljubesi** [comment]
Hey, we do support torch1.7 now, as was tested in https://github.com/clarinsi/classla/issues/12.
