### ISSUE TITLE
Problems with tokeniser

### ISSUE THREAD

**Issue by TomazErjavec** [clarinsi/classla-stanfordnlp#8]
I followed the steps in the readme, i.e. pip install and then "Getting started". The first two steps went ok, but on the third one it complains:

```
Download complete.  Models saved to: /home/tomaz/classla_resources/sl_ssj_models
>>> nlp = classla.Pipeline('sl')
Use device: cpu
---
Loading: tokenize
With settings:
{'model_path': '/home/tomaz/classla_resources/sl_ssj_models/sl_ssj_tokenizer.pt', 'lang': 'sl', 'shorthand': 'sl_ssj', 'mode': 'predict', 'type': 'standard'}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/classla-stanfordnlp/classla/pipeline/core.py", line 144, in __init__
    use_gpu=self.use_gpu)
  File "/usr/local/classla-stanfordnlp/classla/pipeline/processor.py", line 102, in __init__
    self._set_up_model(config, use_gpu)
  File "/usr/local/classla-stanfordnlp/classla/pipeline/tokenize_processor.py", line 25, in _set_up_model
    self._reldi_tokenizer = ReldiTokenizer(config.get('lang'), config.get('type'))
  File "/usr/local/classla-stanfordnlp/classla/utils/reldi.py", line 28, in __init__
    from classla.submodules.reldi_tokeniser import tokeniser
ImportError: cannot import name 'tokeniser' from 'classla.submodules.reldi_tokeniser' (unknown location)
```
Any idea what is going wrong?

**Comment by lkrsnik** [comment]
I am unsure how you used `pip install`. If you used `pip install classla` everything should work as intended. There are two ways I can think of to trigger this error:

1. Cloning this repo and using `pip install .`, without cloning git submodules.
2. By being in classla-stanfordnlp folder with uninstalled submodules.

Solution in both cases is to  download submodules. Example commands:
```
git clone https://github.com/clarinsi/classla-stanfordnlp.git
cd classla-stanfordnlp
git submodule update --init
pip install .
```

**Comment by nljubesi** [comment]
Or Tomaž simply does ```pip install classla``` and / or runs the interpreter while not in the ```classla-stanfordnlp``` folder. It is better we go back to the track of doing things the most simple way.

Tomaž, if you are not sure whether you managed to trigger the submodule issue with any of the two approaches Luka mentioned, it would be best you gave us the exact commands with pwds that you ran while pip installing.

**Comment by TomazErjavec** [comment]
Thanks both for your help! What I did was:

> Cloning this repo and using pip install ., without cloning git submodules.

So, yes, I should've, as Nikola rightly points out, just have done `pip install classla` without cloning. Did that now, and it works. Just goes to show how little I know about Python... So, closing.
