### ISSUE TITLE
Unwanted processing logs in STDOUT

### ISSUE THREAD

**Issue by TomazErjavec** [clarinsi/classla-stanfordnlp#9]
I am used to processing text by reading from STDIN and writing to STDOUT. So, with my limited knowledge of Python, I wrote this simple program to do that:

```
import fileinput
import classla
#classla.download('sl')
nlp = classla.Pipeline('sl')
for line in fileinput.input():
    line.rstrip()
    doc = nlp(line)
    print(doc.conll_file.conll_as_string())
```

and it works just fine, except that on the STDOUT I get the processing log as well, i.e.

```
Use device: cpu
---
Loading: tokenize
...
Done loading processors!
---
```

and only then does the actual CoNLL-U output begin.

It is not a huge deal to get rid of these intro log messages in the output file, still it would be more convenient if they weren't there in the first place. 

So, it is possible to turn off these messsages? Or, maybe even better, rather print to to STDERR?

**Comment by nljubesi** [comment]
I think these should be sent to sys.stderr. Luka, would this be simple to resolve? Thanks!

**Comment by lkrsnik** [comment]
Thank you for suggestion. Logging has been completely reworked by stanza. Right now we are finalizing big classla update, where we also include their latest changes. 

Among other things, logging there is moved to STDERR there, so this should work as described in our next release.
